// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_like_rpc.proto

#ifndef PROTOBUF_INCLUDED_http_5flike_5frpc_2eproto
#define PROTOBUF_INCLUDED_http_5flike_5frpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_http_5flike_5frpc_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_http_5flike_5frpc_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_http_5flike_5frpc_2eproto();
namespace HttpLikeRpc {
class HttpLikeObject;
class HttpLikeObjectDefaultTypeInternal;
extern HttpLikeObjectDefaultTypeInternal _HttpLikeObject_default_instance_;
class HttpLikeObject_MapArgBinEntry_DoNotUse;
class HttpLikeObject_MapArgBinEntry_DoNotUseDefaultTypeInternal;
extern HttpLikeObject_MapArgBinEntry_DoNotUseDefaultTypeInternal _HttpLikeObject_MapArgBinEntry_DoNotUse_default_instance_;
class HttpLikeObject_MapArgStringEntry_DoNotUse;
class HttpLikeObject_MapArgStringEntry_DoNotUseDefaultTypeInternal;
extern HttpLikeObject_MapArgStringEntry_DoNotUseDefaultTypeInternal _HttpLikeObject_MapArgStringEntry_DoNotUse_default_instance_;
}  // namespace HttpLikeRpc
namespace google {
namespace protobuf {
template<> ::HttpLikeRpc::HttpLikeObject* Arena::CreateMaybeMessage<::HttpLikeRpc::HttpLikeObject>(Arena*);
template<> ::HttpLikeRpc::HttpLikeObject_MapArgBinEntry_DoNotUse* Arena::CreateMaybeMessage<::HttpLikeRpc::HttpLikeObject_MapArgBinEntry_DoNotUse>(Arena*);
template<> ::HttpLikeRpc::HttpLikeObject_MapArgStringEntry_DoNotUse* Arena::CreateMaybeMessage<::HttpLikeRpc::HttpLikeObject_MapArgStringEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace HttpLikeRpc {

// ===================================================================

class HttpLikeObject_MapArgStringEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<HttpLikeObject_MapArgStringEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<HttpLikeObject_MapArgStringEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  HttpLikeObject_MapArgStringEntry_DoNotUse();
  HttpLikeObject_MapArgStringEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const HttpLikeObject_MapArgStringEntry_DoNotUse& other);
  static const HttpLikeObject_MapArgStringEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const HttpLikeObject_MapArgStringEntry_DoNotUse*>(&_HttpLikeObject_MapArgStringEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class HttpLikeObject_MapArgBinEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<HttpLikeObject_MapArgBinEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_BYTES,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<HttpLikeObject_MapArgBinEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_BYTES,
    0 > SuperType;
  HttpLikeObject_MapArgBinEntry_DoNotUse();
  HttpLikeObject_MapArgBinEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const HttpLikeObject_MapArgBinEntry_DoNotUse& other);
  static const HttpLikeObject_MapArgBinEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const HttpLikeObject_MapArgBinEntry_DoNotUse*>(&_HttpLikeObject_MapArgBinEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class HttpLikeObject final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HttpLikeRpc.HttpLikeObject) */ {
 public:
  HttpLikeObject();
  virtual ~HttpLikeObject();

  HttpLikeObject(const HttpLikeObject& from);

  inline HttpLikeObject& operator=(const HttpLikeObject& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HttpLikeObject(HttpLikeObject&& from) noexcept
    : HttpLikeObject() {
    *this = ::std::move(from);
  }

  inline HttpLikeObject& operator=(HttpLikeObject&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const HttpLikeObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HttpLikeObject* internal_default_instance() {
    return reinterpret_cast<const HttpLikeObject*>(
               &_HttpLikeObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(HttpLikeObject* other);
  friend void swap(HttpLikeObject& a, HttpLikeObject& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HttpLikeObject* New() const final {
    return CreateMaybeMessage<HttpLikeObject>(nullptr);
  }

  HttpLikeObject* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HttpLikeObject>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HttpLikeObject& from);
  void MergeFrom(const HttpLikeObject& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HttpLikeObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> map_arg_string = 3;
  int map_arg_string_size() const;
  void clear_map_arg_string();
  static const int kMapArgStringFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      map_arg_string() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_map_arg_string();

  // map<string, bytes> map_arg_bin = 4;
  int map_arg_bin_size() const;
  void clear_map_arg_bin();
  static const int kMapArgBinFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      map_arg_bin() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_map_arg_bin();

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // uint32 code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::uint32 code() const;
  void set_code(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:HttpLikeRpc.HttpLikeObject)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      HttpLikeObject_MapArgStringEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > map_arg_string_;
  ::google::protobuf::internal::MapField<
      HttpLikeObject_MapArgBinEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_BYTES,
      0 > map_arg_bin_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::uint32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_http_5flike_5frpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HttpLikeObject

// uint32 code = 1;
inline void HttpLikeObject::clear_code() {
  code_ = 0u;
}
inline ::google::protobuf::uint32 HttpLikeObject::code() const {
  // @@protoc_insertion_point(field_get:HttpLikeRpc.HttpLikeObject.code)
  return code_;
}
inline void HttpLikeObject::set_code(::google::protobuf::uint32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:HttpLikeRpc.HttpLikeObject.code)
}

// string message = 2;
inline void HttpLikeObject::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HttpLikeObject::message() const {
  // @@protoc_insertion_point(field_get:HttpLikeRpc.HttpLikeObject.message)
  return message_.GetNoArena();
}
inline void HttpLikeObject::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpLikeRpc.HttpLikeObject.message)
}
#if LANG_CXX11
inline void HttpLikeObject::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HttpLikeRpc.HttpLikeObject.message)
}
#endif
inline void HttpLikeObject::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpLikeRpc.HttpLikeObject.message)
}
inline void HttpLikeObject::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpLikeRpc.HttpLikeObject.message)
}
inline ::std::string* HttpLikeObject::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:HttpLikeRpc.HttpLikeObject.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HttpLikeObject::release_message() {
  // @@protoc_insertion_point(field_release:HttpLikeRpc.HttpLikeObject.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HttpLikeObject::set_allocated_message(::std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:HttpLikeRpc.HttpLikeObject.message)
}

// map<string, string> map_arg_string = 3;
inline int HttpLikeObject::map_arg_string_size() const {
  return map_arg_string_.size();
}
inline void HttpLikeObject::clear_map_arg_string() {
  map_arg_string_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
HttpLikeObject::map_arg_string() const {
  // @@protoc_insertion_point(field_map:HttpLikeRpc.HttpLikeObject.map_arg_string)
  return map_arg_string_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
HttpLikeObject::mutable_map_arg_string() {
  // @@protoc_insertion_point(field_mutable_map:HttpLikeRpc.HttpLikeObject.map_arg_string)
  return map_arg_string_.MutableMap();
}

// map<string, bytes> map_arg_bin = 4;
inline int HttpLikeObject::map_arg_bin_size() const {
  return map_arg_bin_.size();
}
inline void HttpLikeObject::clear_map_arg_bin() {
  map_arg_bin_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
HttpLikeObject::map_arg_bin() const {
  // @@protoc_insertion_point(field_map:HttpLikeRpc.HttpLikeObject.map_arg_bin)
  return map_arg_bin_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
HttpLikeObject::mutable_map_arg_bin() {
  // @@protoc_insertion_point(field_mutable_map:HttpLikeRpc.HttpLikeObject.map_arg_bin)
  return map_arg_bin_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace HttpLikeRpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_http_5flike_5frpc_2eproto
