// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: http_like_rpc.proto
#ifndef GRPC_http_5flike_5frpc_2eproto__INCLUDED
#define GRPC_http_5flike_5frpc_2eproto__INCLUDED

#include "http_like_rpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace HttpLikeRpc {

// The greeting service definition.
class HttpLike final {
 public:
  static constexpr char const* service_full_name() {
    return "HttpLikeRpc.HttpLike";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Post(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::HttpLikeRpc::HttpLikeObject* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HttpLikeRpc::HttpLikeObject>> AsyncPost(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HttpLikeRpc::HttpLikeObject>>(AsyncPostRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HttpLikeRpc::HttpLikeObject>> PrepareAsyncPost(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HttpLikeRpc::HttpLikeObject>>(PrepareAsyncPostRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Post(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Post(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::HttpLikeRpc::HttpLikeObject* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HttpLikeRpc::HttpLikeObject>* AsyncPostRaw(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HttpLikeRpc::HttpLikeObject>* PrepareAsyncPostRaw(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Post(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::HttpLikeRpc::HttpLikeObject* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HttpLikeRpc::HttpLikeObject>> AsyncPost(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HttpLikeRpc::HttpLikeObject>>(AsyncPostRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HttpLikeRpc::HttpLikeObject>> PrepareAsyncPost(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HttpLikeRpc::HttpLikeObject>>(PrepareAsyncPostRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Post(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response, std::function<void(::grpc::Status)>) override;
      void Post(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::HttpLikeRpc::HttpLikeObject* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::HttpLikeRpc::HttpLikeObject>* AsyncPostRaw(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HttpLikeRpc::HttpLikeObject>* PrepareAsyncPostRaw(::grpc::ClientContext* context, const ::HttpLikeRpc::HttpLikeObject& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Post_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Post : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Post() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Post() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPost(::grpc::ServerContext* context, ::HttpLikeRpc::HttpLikeObject* request, ::grpc::ServerAsyncResponseWriter< ::HttpLikeRpc::HttpLikeObject>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Post<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Post : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Post() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::HttpLikeRpc::HttpLikeObject, ::HttpLikeRpc::HttpLikeObject>(
          [this](::grpc::ServerContext* context,
                 const ::HttpLikeRpc::HttpLikeObject* request,
                 ::HttpLikeRpc::HttpLikeObject* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Post(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Post() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Post<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Post : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Post() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Post() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Post : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Post() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Post() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPost(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Post : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Post() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Post(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Post() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Post(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Post : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Post() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::HttpLikeRpc::HttpLikeObject, ::HttpLikeRpc::HttpLikeObject>(std::bind(&WithStreamedUnaryMethod_Post<BaseClass>::StreamedPost, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Post() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Post(::grpc::ServerContext* context, const ::HttpLikeRpc::HttpLikeObject* request, ::HttpLikeRpc::HttpLikeObject* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPost(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HttpLikeRpc::HttpLikeObject,::HttpLikeRpc::HttpLikeObject>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Post<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Post<Service > StreamedService;
};

}  // namespace HttpLikeRpc


#endif  // GRPC_http_5flike_5frpc_2eproto__INCLUDED
